# General settings for mediator agent
# Mediator does not use a ledger
no-ledger: true

# Wallet
auto-provision: true

# Mediation
open-mediation: true
enable-undelivered-queue: true

# Connections
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Print an admin invite
connections-invite: true
invite-multi-use: true