kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}-build-template
  creationTimestamp: null
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${APP_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${APP_NAME}
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
    strategy:
      type: Docker
    source:
      type: Git
      git:
        uri: "https://github.com/bcgov/openshift-aries-mediator-service.git"
        ref: main
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
      dockerfile: >
        FROM
        artifacts.developer.gov.bc.ca/github-docker-remote/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.8.0-rc0

        USER root

        # The root group needs access the directories under $HOME/.indy_client for
        # the container to function in OpenShift. Also ensure the permissions on 
        # python 'site-packages' folder are set correctly.

        RUN chown -R indy:root $HOME/.indy_client \
            && chmod -R ug+rw $HOME/log $HOME/ledger $HOME/.aries_cloudagent $HOME/.cache $HOME/.indy-cli $HOME/.indy_client \
            && chmod +rx $(python -m site --user-site)

        USER $user

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources defined in this template.
    required: true
    value: aries-mediator-agent
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value:
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together.
    required: true
    value: aries-mediator-service
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
